
# Generated by CodiumAI
from triplea.service.repository.state.custom.affiliation_mining import get_affiliation_structured


import pytest

class TestGetAffiliationStructured:

    # Test with a simple affiliation text containing only a university
    def test_simple_affiliation_text_with_university(self):
        affiliation_text = "Nuffield Department of Population Health, University of Oxford, Oxford, UK"
        expected_result = [{'department': 'Nuffield Department of Population Health'}, {'university': 'University of Oxford'}, {'country': 'UK'}]
        assert get_affiliation_structured(affiliation_text) == expected_result

    # Test with a simple affiliation text containing only a center
    def test_simple_affiliation_text_with_center(self):
        affiliation_text = "Center of Excellence in Medical Genetics Research, Faculty of Dentistry, Chiang Mai University, Chiang Mai 50200, Thailand"
        expected_result = [{'center': 'Center of Excellence in Medical Genetics Research'}, {'university': 'Chiang Mai University'}, {'country': 'Thailand'}]
        assert get_affiliation_structured(affiliation_text) == expected_result

    # Test with a simple affiliation text containing only a department
    def test_simple_affiliation_text_with_department(self):
        affiliation_text = "Department of Ophthalmology, University of Washington, Seattle, Washington, USA"
        expected_result = [{'department': 'Department of Ophthalmology'}, {'university': 'University of Washington'}, {'country': 'USA'}]
        assert get_affiliation_structured(affiliation_text) == expected_result

    # Test with empty affiliation text
    def test_empty_affiliation_text(self):
        affiliation_text = ""
        expected_result = None
        assert get_affiliation_structured(affiliation_text) == expected_result

    # Test with None affiliation text
    def test_none_affiliation_text(self):
        affiliation_text = None
        expected_result = None
        assert get_affiliation_structured(affiliation_text) == expected_result

    # Test with affiliation text containing only unknown affiliations
    def test_affiliation_text_with_unknown_affiliations(self):
        affiliation_text = "Unknown Affiliation"
        expected_result = [{'country': 'NaN'}]
        assert get_affiliation_structured(affiliation_text) == expected_result