
# Generated by CodiumAI
from triplea.cli.export import export
import os
from click.testing import CliRunner

import pytest

class TestExport:

    # Exporting article repository in rayyan csv format
    def test_export_rayyan_csv(self):
        output_file = "output.csv"
        runner = CliRunner()
        result = runner.invoke(
            export,
            [
                "--type", "rayyan",
                "--format", "csv",
                "--limit", 0,
                "--output", output_file
            ]
        )

        assert result.exit_code == 0
        assert "Article(s)" in result.output
        assert "Export Complete" in result.output

        # Assert that the output file exists
        assert os.path.exists(output_file)

        # Clean up the output file
        os.remove(output_file)

    # Exporting article repository in triplea json format
    def test_export_triplea_json(self):
        output_file = "output.json"
        runner = CliRunner()
        result = runner.invoke(
            export,
            [
                "--type", "triplea",
                "--format", "json",
                "--limit", 0,
                "--output", output_file
            ]
        )

        assert result.exit_code == 0
        assert "Article(s)" in result.output
        assert "Export Complete" in result.output

        # Assert that the output file exists
        assert os.path.exists(output_file)

        # Clean up the output file
        os.remove(output_file)


    # Exporting article repository with invalid export type
    def test_export_invalid_export_type(self):
        # with pytest.raises(Exception):
        #     output_file = "output.json"
        #     runner = CliRunner()
        #     result = runner.invoke(
        #         export,
        #         [
        #             "--type", "triplea11",
        #             "--format", "json",
        #             "--limit", 0,
        #             "--output", output_file
        #         ]
        #     )

        output_file = "output.json"
        runner = CliRunner()
        result = runner.invoke(
            export,
            [
                "--type", "photoshop",
                "--format", "json",
                "--limit", 0,
                "--output", output_file
            ]
        )
        assert result.exit_code == 2
        assert "Invalid value for '--type'" in result.output

    # Exporting article repository with invalid format type
    def test_export_invalid_format_type(self):
        output_file = "output.json"
        runner = CliRunner()
        result = runner.invoke(
            export,
            [
                "--type", "triplea",
                "--format", "bin",
                "--limit", 0,
                "--output", output_file
            ]
        )
        assert result.exit_code == 2
        assert "Invalid value for '--format'" in result.output
