__version__ = "0.0.2"
__title__ = "Triplea"
__description__ = "Article Analysis Assistant "
__url__ = "https://github.com/EhsanBitaraf/triple-a"
__author__ = "Ehsan Bitaraf <ehsan.bitaraf@gmail.com>"
__email__ = "ehsan.bitaraf@gmail.com"
__license__ = "GNU Lesser General Public License, version 2.1"
__copyright__ = ""
